Repository connect-foundation/2019-08, pull requests merged in 2019-12, with the labels that each got.

#89 Hotfix
  client/src/core/entity/post.tsx
  client/src/presentation/components/snug/chat-container/index.tsx
  client/src/presentation/components/snug/chat-input-box/index.tsx
  client/src/presentation/pages/snug/message-section/content.tsx
Labels: bug

#92 ID 기반의 Pagination 전략 추가
  server/package-lock.json
  server/package.json
  server/src/controller/api/common/order.ts
  server/src/controller/api/common/pagenation/paginator.ts
  server/src/controller/api/common/pagenation/strategy/default-page.ts
  server/src/controller/api/common/pagenation/strategy/id-page.ts
  server/src/controller/api/common/pagenation/strategy/page.ts
  server/src/controller/api/common/pagenation/strategy/util/purifier.ts
  server/src/controller/api/common/paginator.ts
  server/src/controller/api/post-controller.ts
  server/src/entity/Post.ts
  server/src/routes/channel/channel-router.ts
  server/src/validator/identifier-validator.ts
  server/test/integrate/channel/post/post-controller.test.ts
  server/test/unit/controller/api/common/order.test.ts
  server/test/unit/controller/api/common/paginator.test.ts
Labels: devback, enhancement

#116 Feature front logout
  client/src/core/service/auth-service.ts
  client/src/core/use-case/auth-repository-type.ts
  client/src/data/repository/auth-repository.ts
  client/src/presentation/components/atomic-reusable/global-header.tsx
  client/src/presentation/components/atomic-reusable/page-layout.tsx
  client/src/presentation/pages/home/index.tsx
  client/src/presentation/pages/register-snug/index.tsx
  client/src/presentation/pages/register-user/index.tsx
Labels: devfront, feature

#115 Feature front login
  client/package-lock.json
  client/package.json
  client/src/@context/http-providers/http-providers.tsx
  client/src/@context/repositories/index.tsx
  client/src/@context/services/index.tsx
  client/src/@context/storage-providers/storage-providers.tsx
  client/src/core/entity/token.ts
  client/src/core/entity/user.ts
  client/src/core/model/json-web-token-model.ts
  client/src/core/service/auth-service.ts
  client/src/core/use-case/auth-repository-type.ts
  client/src/data/browser-storage/browser-storage-helper.ts
  client/src/data/browser-storage/browser-storage-mapper.ts
  client/src/data/browser-storage/browser-storage.ts
  client/src/data/browser-storage/custom-mapper/json-web-tocken-mapper.ts
  client/src/data/http/api/auth-api.ts
  client/src/data/http/api/axios-wrapper.ts
  client/src/data/http/api/channel-api.ts
  client/src/data/repository/auth-repository.ts
  client/src/presentation/components/atomic-reusable/custom-login-input.tsx
  client/src/presentation/components/atomic-reusable/global-header.tsx
  client/src/presentation/components/atomic-reusable/page-layout.tsx
  client/src/presentation/pages/home/home-form.tsx
  client/src/presentation/pages/home/home-snug.tsx
  client/src/presentation/pages/home/index.tsx
  client/src/presentation/pages/register-snug/index.tsx
  client/src/presentation/pages/register-user/index.tsx
  server/src/controller/api/auth-controller.ts
  server/src/controller/api/channel-controller.ts
Labels: devfront, feature

#102 로그인 기능 백엔드 구현
  client/package-lock.json
  client/package.json
  client/src/@context/http-providers/http-providers.tsx
  client/src/@context/repositories/index.tsx
  client/src/@context/services/index.tsx
  client/src/@context/storage-providers/storage-providers.tsx
  client/src/core/entity/token.ts
  client/src/core/entity/user.ts
  client/src/core/model/json-web-token-model.ts
  client/src/core/service/auth-service.ts
  client/src/core/use-case/auth-repository-type.ts
  client/src/data/browser-storage/browser-storage-helper.ts
  client/src/data/browser-storage/browser-storage-mapper.ts
  client/src/data/browser-storage/browser-storage.ts
  client/src/data/browser-storage/custom-mapper/json-web-tocken-mapper.ts
  client/src/data/http/api/auth-api.ts
  client/src/data/http/api/axios-wrapper.ts
  client/src/data/http/api/channel-api.ts
  client/src/data/repository/auth-repository.ts
  client/src/presentation/components/atomic-reusable/custom-login-input.tsx
  client/src/presentation/components/atomic-reusable/global-header.tsx
  client/src/presentation/components/atomic-reusable/page-layout.tsx
  client/src/presentation/pages/home/home-form.tsx
  client/src/presentation/pages/home/home-snug.tsx
  client/src/presentation/pages/home/index.tsx
  client/src/presentation/pages/register-snug/index.tsx
  client/src/presentation/pages/register-user/index.tsx
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controller/api/auth-controller.ts
  server/src/controller/api/channel-controller.ts
  server/src/routes/auth/auth-router.ts
  server/src/validator/identifier-validator.ts
Labels: API, devback, feature

#109 user 가입시키는 기능
  client/src/@context/http-providers/http-providers.tsx
  client/src/@context/repositories/index.tsx
  client/src/@context/repositories/user.ts
  client/src/@context/services/index.tsx
  client/src/core/entity/user.ts
  client/src/core/service/user-service.ts
  client/src/core/use-case/user-repository-type.ts
  client/src/data/http/api/user-api.ts
  client/src/data/repository/user-repository.ts
  client/src/presentation/components/atomic-reusable/custom-button.tsx
  client/src/presentation/components/atomic-reusable/custom-login-input.tsx
  client/src/presentation/components/register-user/inputs/email-input.tsx
  client/src/presentation/components/register-user/inputs/inputs-prop-types.tsx
  client/src/presentation/components/register-user/inputs/name-input.tsx
  client/src/presentation/components/register-user/inputs/password-check-input.tsx
  client/src/presentation/components/register-user/inputs/password-input.tsx
  client/src/presentation/components/register-user/modal/index.tsx
  client/src/presentation/pages/home/home-form.tsx
  client/src/presentation/pages/register-user/index.tsx
  client/src/presentation/pages/register-user/register-user-form.tsx
  client/src/presentation/validation/validation.ts
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controller/api/channel-controller.ts
  server/src/controller/api/common/error-message.ts
  server/src/controller/api/common/messages.ts
  server/src/controller/api/post-controller.ts
  server/src/controller/api/user-controller.ts
  server/src/entity/Snug.ts
  server/src/entity/User.ts
  server/src/middleware/validator.ts
  server/src/migration/1575357161313-ALTER-USERCOLUMN.ts
  server/src/migration/1575362426119-ALTER-USEREMAIL.ts
  server/src/routes/channel/channel-router.ts
  server/src/routes/user/user-router.ts
  server/src/utils/password/generate-password.ts
  server/src/validator/email-validator.ts
Labels: API, devback, devfront

#110 사용자가 스너그를 생성하는 로직 구현
  .vscode/launch.json
  client/src/@context/http-providers/http-providers.tsx
  client/src/@context/repositories/index.tsx
  client/src/@context/repositories/snug.ts
  client/src/@context/services/index.tsx
  client/src/App.tsx
  client/src/contexts/messages-context.tsx
  client/src/core/entity/post.tsx
  client/src/core/entity/profile.ts
  client/src/core/entity/snug.ts
  client/src/core/service/post-service.ts
  client/src/core/service/snug-service.ts
  client/src/core/use-case/post-repository-type.ts
  client/src/core/use-case/snug-repository-type.ts
  client/src/data/http/api/post-api.ts
  client/src/data/http/api/snug-api.ts
  client/src/data/repository/post-repository.ts
  client/src/data/repository/snug-repository.ts
  client/src/presentation/components/atomic-reusable/global-header.tsx
  client/src/presentation/pages/home/home-form.tsx
  client/src/presentation/pages/register-snug/index.tsx
  client/src/presentation/pages/register-snug/modal.tsx
  client/src/presentation/pages/register-snug/register-snug-form.tsx
  client/src/presentation/pages/register-user/index.tsx
  server/.env.template
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controller/api/auth-controller.ts
  server/src/controller/api/post-controller.ts
  server/src/controller/api/snug-controller.ts
  server/src/entity/Snug.ts
  server/src/routes/snug/snug-router.ts
  server/src/validator/identifier-validator.ts
Labels: devback, devfront, feature

#118 초대 이메일 및 알림 전송 기능
  server/.env.template
  server/ormconfig.js
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controller/api/auth-controller.ts
  server/src/controller/api/channel-controller.ts
  server/src/controller/api/common/messages.ts
  server/src/controller/api/common/status-code.ts
  server/src/controller/api/invite-controller.ts
  server/src/controller/api/post-controller.ts
  server/src/controller/api/snug-controller.ts
  server/src/controller/api/user-controller.ts
  server/src/controller/index-controller.ts
  server/src/domain/entity/Base.ts
  server/src/domain/entity/Invite.ts
  server/src/domain/entity/ParticipateIn.ts
  server/src/domain/entity/Post.ts
  server/src/domain/entity/Profile.ts
  server/src/domain/entity/Room.ts
  server/src/domain/entity/Snug.ts
  server/src/domain/entity/User.ts
  server/src/domain/vo/Email.ts
  server/src/entity/User.ts
  server/src/middleware/errorHandler.ts
  server/src/migration/1575540485123-ADD-INVITE.ts
  server/src/migration/1575542819077-CHANGE-EMAIL-AS-COMPOSITE-KEY.ts
  server/src/model/inviter.ts
  server/src/model/notifier/email-notifier.ts
  server/src/model/notifier/invite-notifier.ts
  server/src/model/notifier/notifier.ts
  server/src/routes/index.ts
  server/src/routes/invite/invite-router.ts
  server/src/routes/snug/invite/invite-router.ts
  server/src/routes/snug/snug-router.ts
  server/src/socket/action/invite.ts
  server/src/socket/action/room.ts
  server/src/socket/common/events/publish-type.ts
  server/src/socket/listener/connection.ts
  server/src/template/email-contents.ts
  server/src/utils/array-helper.ts
  server/src/utils/exception/HttpException.ts
  server/src/utils/url-info.ts
  server/src/validator/identifier-validator.ts
  server/test/integrate/channel/channel-controller.test.ts
  server/test/integrate/channel/post/post-controller.test.ts
  server/test/unit/controller/channel-controller.test.ts
  server/test/unit/controller/post-controller.test.ts
Labels: devback, feature

#103 초대할 Email 리스트를 API 서버에 전송하는 기능 추가
  client/src/@context/http-providers/http-providers.tsx
  client/src/@context/repositories/index.tsx
  client/src/@context/repositories/invite.ts
  client/src/@context/services/index.tsx
  client/src/App.tsx
  client/src/core/model/email-model.ts
  client/src/core/service/invite-service.ts
  client/src/core/use-case/invite-repository-type.ts
  client/src/data/http/api/invite-api.ts
  client/src/data/repository/invite-repository.ts
  client/src/presentation/pages/invite-users/container/index.tsx
  client/src/presentation/pages/invite-users/form/Invite-button.tsx
  client/src/presentation/pages/invite-users/form/index.tsx
  client/src/presentation/pages/invite-users/index.tsx
  client/src/prop-types/invite-match-type.ts
  client/src/prop-types/match-extends-types.ts
Labels: devfront, feature

#100 Snug 생성후, "초대하기" 기능에 대한 UI 추가
  client/src/@context/http-providers/http-providers.tsx
  client/src/@context/repositories/index.tsx
  client/src/@context/repositories/invite.ts
  client/src/@context/services/index.tsx
  client/src/App.tsx
  client/src/core/model/email-model.ts
  client/src/core/service/invite-service.ts
  client/src/core/use-case/invite-repository-type.ts
  client/src/core/utility/array-helper.ts
  client/src/core/utility/compose-helper.ts
  client/src/data/http/api/invite-api.ts
  client/src/data/repository/invite-repository.ts
  client/src/presentation/pages/invite-users/container/index.tsx
  client/src/presentation/pages/invite-users/description/index.tsx
  client/src/presentation/pages/invite-users/form/Invite-button.tsx
  client/src/presentation/pages/invite-users/form/index.tsx
  client/src/presentation/pages/invite-users/form/invite-users.tsx
  client/src/presentation/pages/invite-users/index.tsx
  client/src/prop-types/invite-match-type.ts
  client/src/prop-types/match-extends-types.ts
  server/src/utils/url-info.ts
Labels: devfront, feature

#119 로그인 후 홈 화면에서 snug list 렌더링
  client/src/core/service/snug-service.ts
  client/src/core/use-case/snug-repository-type.ts
  client/src/data/http/api/snug-api.ts
  client/src/data/repository/snug-repository.ts
  client/src/presentation/pages/home/home-detail-snug.tsx
  client/src/presentation/pages/home/home-snug.tsx
  client/src/presentation/pages/home/index.tsx
  server/package-lock.json
  server/package.json
  server/src/controller/api/common/messages.ts
  server/src/controller/api/snug-controller.ts
  server/src/model/notifier/email-notifier.ts
  server/src/routes/snug/snug-router.ts
Labels: devback, devfront, enhancement

#133 로그인 과정에서 typerom이 User를 제대로 찾지 못하는 문제 수정
  client/src/presentation/pages/home/home-snug.tsx
  server/src/controller/api/auth-controller.ts
Labels: bug

#143 snug 페이지 접근시 url 버그 수정
  client/src/App.tsx
  client/src/contexts/path-parameter-context.tsx
  client/src/core/entity/path-parameter.ts
  client/src/presentation/components/snug/channel-list/channel-title.tsx
  client/src/presentation/components/snug/channel-list/index.tsx
  client/src/presentation/pages/snug/index.tsx
Labels: bug, devfront

#149 이메일 전송 관리하는 Mail-Manager 추가
  .gitignore
  server/.env.template
  server/src/controller/api/auth-controller.ts
  server/src/controller/api/snug-controller.ts
  server/src/controller/api/user-controller.ts
  server/src/domain/entity/Invite.ts
  server/src/domain/entity/ParticipateIn.ts
  server/src/domain/entity/Room.ts
  server/src/domain/entity/User.ts
  server/src/domain/vo/Email.ts
  server/src/mail/mail-manager.ts
  server/src/model/invite/invitee.ts
  server/src/model/invite/inviter.ts
  server/src/model/notifier/email-notifier.ts
  server/src/model/notifier/invite-notifier.ts
  server/src/model/notifier/notifier.ts
  server/src/model/participant/participant.ts
  server/src/server.ts
  server/src/utils/array-helper.ts
  server/src/utils/exception/TransferEmailException.ts
Labels: bug, devback, enhancement

#145 feat : 채널에 참여하는 fetch 구현
  client/src/core/service/channel-service.ts
  client/src/core/use-case/channel-repository-type.ts
  client/src/data/http/api/channel-api.ts
  client/src/data/repository/channel-repository.ts
Labels: devfront, feature

#151 Feature channellistmodal ui
  client/src/App.tsx
  client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-item.tsx
  server/package-lock.json
Labels: devfront, feature

#148 Feature api preview
  server/src/controller/api/auth-controller.ts
  server/src/controller/api/channel-controller.ts
  server/src/routes/channel/channel-router.ts
Labels: API, devback

#144 Feature api profile
  server/src/controller/api/auth-controller.ts
  server/src/controller/api/channel-controller.ts
  server/src/controller/api/profile-controller.ts
  server/src/domain/entity/Profile.ts
  server/src/routes/auth/auth-router.ts
  server/src/routes/channel/channel-router.ts
  server/src/routes/snug/snug-router.ts
  server/src/validator/identifier-validator.ts
Labels: API, devback

#152 user socket과 snug 소켓을 분리하여 구현
  client/src/App.tsx
  client/src/contexts/socket-context.tsx
  client/src/presentation/components/invitation-alarm/index.tsx
  client/src/presentation/components/snug/channel-list/index.tsx
  client/src/presentation/components/snug/chat-container/index.tsx
  client/src/presentation/components/snug/chat-input-box/index.tsx
  client/src/presentation/pages/home/home-snug.tsx
  client/src/presentation/pages/invite-users/container/index.tsx
  client/src/presentation/pages/invite-users/form/index.tsx
  client/src/presentation/pages/invite-users/index.tsx
  client/src/presentation/pages/register-user/index.tsx
  client/src/presentation/pages/snug/index.tsx
  client/src/presentation/pages/snug/message-section/content.tsx
  client/src/presentation/pages/snug/message-section/index.tsx
  client/src/presentation/pages/snug/sidebar/index.tsx
  client/src/prop-types/match-extends-types.ts
Labels: bug, devfront

#161 Deature profile cookie
  client/src/core/service/profile-service.ts
  client/src/core/use-case/profile-repository-type.ts
  client/src/data/http/api/profile-api.ts
  client/src/data/repository/profile-repository.ts
  client/src/util/cookie.ts
  server/src/controller/api/auth-controller.ts
  server/src/controller/api/channel-controller.ts
Labels: devfront, feature

#155 프로필 조회 및 수정 기능
  client/src/App.tsx
  client/src/contexts/socket-context.tsx
  client/src/presentation/components/invitation-alarm/index.tsx
  client/src/presentation/components/snug/channel-list/index.tsx
  client/src/presentation/components/snug/chat-container/index.tsx
  client/src/presentation/components/snug/chat-input-box/index.tsx
  client/src/presentation/pages/home/home-snug.tsx
  client/src/presentation/pages/invite-users/container/index.tsx
  client/src/presentation/pages/invite-users/form/index.tsx
  client/src/presentation/pages/invite-users/index.tsx
  client/src/presentation/pages/register-user/index.tsx
  client/src/presentation/pages/snug/index.tsx
  client/src/presentation/pages/snug/message-section/content.tsx
  client/src/presentation/pages/snug/message-section/index.tsx
  client/src/presentation/pages/snug/sidebar/index.tsx
  client/src/prop-types/match-extends-types.ts
  server/.eslintrc
  server/.gitignore
  server/public/image/default-thumbnail.jpeg
  server/src/app.ts
  server/src/controller/api/auth-controller.ts
  server/src/controller/api/common/messages.ts
  server/src/controller/api/common/token/profile-token.ts
  server/src/controller/api/common/token/token.ts
  server/src/controller/api/common/token/user-token.ts
  server/src/controller/api/profile-controller.ts
  server/src/domain/entity/Profile.ts
  server/src/migration/1575997516122-ADD-PHONE-AND-CHANGE-USER-JOIN-COLUMN.ts
  server/src/model/profile/profile-info.ts
  server/src/model/profile/profiler.ts
  server/src/routes/profile/profile-router.ts
Labels: devback, feature

#170 Profile Token 항목으로 status, email, description 추가
  server/src/controller/api/auth-controller.ts
  server/src/controller/api/common/messages.ts
  server/src/controller/api/common/token/profile-token.ts
  server/src/domain/entity/Invite.ts
  server/src/domain/vo/Email.ts
  server/src/domain/vo/Ticket.ts
  server/src/migration/1575729716556-ADD-TICKET-TYPE.ts
  server/src/migration/1575997516122-ADD-PHONE-AND-CHANGE-USER-JOIN-COLUMN.ts
  server/src/migration/1576118484821-ADD-EMAIL-INDEX.ts
  server/src/migration/1576118787009-ADD-TICKET-INDEX.ts
  server/src/model/profile/profile-info.ts
  server/src/template/email-contents.ts
Labels: devback, enhancement

#168 파일을 업로드할 수 있는 UI 기능 구현
  client/src/presentation/components/atomic-reusable/icon-box.tsx
  client/src/presentation/components/snug/chat-input-box/index.tsx
  client/src/presentation/components/snug/file-preview/image-preview.tsx
  client/src/presentation/components/snug/file-preview/index.tsx
  client/src/presentation/components/snug/file-preview/normal-preview.tsx
  client/src/presentation/components/snug/file-upload-modal/file-drop-area.tsx
  client/src/presentation/components/snug/file-upload-modal/index.tsx
  client/src/presentation/pages/snug/message-section/content.tsx
Labels: devfront

#164 Feature api participate
  server/src/app.ts
  server/src/controller/api/participate-in-controller.ts
  server/src/routes/participate-in/index.ts
  server/src/validator/identifier-validator.ts
Labels: API, devback

#163 feat : url을 통해 스너그에 들어 왔을 때 해당하는 채널에 색이 칠이 칠해지도록 기능을 구현함
  client/src/presentation/pages/snug/index.tsx
Labels: bug

#162 Feature participant in fetch
  client/src/core/service/channel-service.ts
  client/src/core/use-case/channel-repository-type.ts
  client/src/data/http/api/channel-api.ts
  client/src/data/repository/channel-repository.ts
Labels: devfront, feature

#137 프리뷰 ui 제작
  client/src/core/service/channel-service.ts
  client/src/core/use-case/channel-repository-type.ts
  client/src/data/http/api/channel-api.ts
  client/src/data/repository/channel-repository.ts
  client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-item.tsx
  client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-sort-list.tsx
  client/src/presentation/components/snug/channel-browse-modal/index.tsx
  client/src/presentation/components/snug/channel-list/channel-title.tsx
  client/src/presentation/components/snug/chat-container/index.tsx
  client/src/presentation/components/snug/chat-input-box/index.tsx
  client/src/presentation/components/snug/modals/index.tsx
  client/src/presentation/components/snug/preview/index.tsx
  client/src/presentation/pages/snug/index.tsx
  client/src/presentation/pages/snug/message-section/content.tsx
  client/src/presentation/theme/color-theme.ts
  server/src/routes/channel/channel-router.ts
Labels: devfront, feature

#154 서버에서 사용자 profile 가져오기
  client/src/@context/http-providers/http-providers.tsx
  client/src/@context/repositories/index.tsx
  client/src/@context/repositories/profile.ts
  client/src/@context/services/index.tsx
  client/src/assets/gipyoo.png
  client/src/assets/left-arrow.png
  client/src/assets/more.png
  client/src/assets/right-arrow.png
  client/src/core/entity/profile.ts
  client/src/core/service/profile-service.ts
  client/src/core/use-case/profile-repository-type.ts
  client/src/data/http/api/profile-api.ts
  client/src/data/http/api/status-codes.ts
  client/src/data/repository/profile-repository.ts
  client/src/presentation/components/atomic-reusable/custom-button.tsx
  client/src/presentation/components/invitation-alarm/index.tsx
  client/src/presentation/components/snug/chat-container/index.tsx
  client/src/presentation/components/snug/chat-input-box/index.tsx
  client/src/presentation/pages/snug/message-section/content.tsx
  client/src/presentation/pages/snug/profile/buttons/index.tsx
  client/src/presentation/pages/snug/profile/header/index.tsx
  client/src/presentation/pages/snug/profile/index.tsx
  client/src/presentation/pages/snug/profile/modal/index.tsx
  client/src/presentation/pages/snug/profile/modal/modal-body.tsx
  client/src/presentation/pages/snug/profile/modal/modal-header.tsx
  client/src/presentation/pages/snug/profile/modal/modal-input.tsx
  client/src/presentation/pages/snug/profile/modal/modal-left-body.tsx
  client/src/presentation/pages/snug/profile/modal/modal-right-body.tsx
  client/src/presentation/pages/snug/profile/modal/thumbnail/index.tsx
  client/src/presentation/pages/snug/profile/status/index.tsx
  client/src/presentation/pages/snug/profile/status/status-bar-header.tsx
  client/src/presentation/pages/snug/profile/status/status-bar.tsx
  client/src/presentation/pages/snug/profile/thumbnail/index.tsx
  client/src/util/cookie.ts
  server/.eslintrc
  server/.gitignore
  server/public/image/default-thumbnail.jpeg
  server/src/app.ts
  server/src/controller/api/auth-controller.ts
  server/src/controller/api/channel-controller.ts
  server/src/controller/api/common/messages.ts
  server/src/controller/api/common/token/profile-token.ts
  server/src/controller/api/common/token/token.ts
  server/src/controller/api/common/token/user-token.ts
  server/src/controller/api/profile-controller.ts
  server/src/controller/api/snug-controller.ts
  server/src/domain/entity/Invite.ts
  server/src/domain/entity/Profile.ts
  server/src/domain/vo/Email.ts
  server/src/domain/vo/Ticket.ts
  server/src/migration/1575729716556-ADD-TICKET-TYPE.ts
  server/src/migration/1575997516122-ADD-PHONE-AND-CHANGE-USER-JOIN-COLUMN.ts
  server/src/migration/1576118484821-ADD-EMAIL-INDEX.ts
  server/src/migration/1576118787009-ADD-TICKET-INDEX.ts
  server/src/model/invite/invite-info.ts
  server/src/model/profile/profile-info.ts
  server/src/model/profile/profiler.ts
  server/src/routes/profile/profile-router.ts
  server/src/template/email-contents.ts
Labels: devback, devfront, feature

#173 fix : 치명적인 오류 해결
  client/src/data/repository/channel-repository.ts
  client/src/presentation/components/snug/chat-input-box/index.tsx
  client/src/presentation/pages/snug/index.tsx
  server/src/controller/api/channel-controller.ts
  server/src/controller/api/participate-in-controller.ts
  server/src/controller/api/post-controller.ts
Labels: bug

#172 메시지 목록 조회시 캐싱 기능 추가
  server/.env.production
  server/.env.template
  server/.gitignore
  server/ormconfig.js
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controller/api/post-controller.ts
  server/src/domain/entity/Post.ts
  server/src/utils/url-info.ts
Labels: devback, enhancement, feature

#174 서버 배포를 위한 pm2와 winston 설정
  client/package-lock.json
  client/package.json
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/middleware/errorHandler.ts
  server/src/routes/apiRouter.ts
  server/src/routes/index.ts
  server/src/server.ts
  server/src/utils/logger.ts
Labels: devback, enhancement

#179 회원가입에서 초대 정보를 조회하지 못하는 이슈
  server/src/controller/api/user-controller.ts
  server/src/domain/entity/Invite.ts
  server/src/model/invite/invitee.ts
Labels: bug, devback

#178 여러 Snug에서 동일한 주소로 이메일 발송하지 못하는 이슈
  server/src/controller/api/user-controller.ts
  server/src/domain/entity/Invite.ts
  server/src/domain/entity/User.ts
  server/src/domain/vo/Email.ts
  server/src/migration/1576161811408-CHANGE-EMAIL-INDEX.ts
  server/src/model/invite/invitee.ts
  server/src/utils/url-info.ts
Labels: bug, devback

#191 Thread API 기능 추가 및 front reply 기능 소켓 연결
  client/src/@context/services/index.tsx
  client/src/core/entity/post.tsx
  client/src/core/entity/thread.ts
  client/src/core/service/post-service.ts
  client/src/core/use-case/post-repository-type.ts
  client/src/data/http/api/post-api.ts
  client/src/data/repository/post-repository.ts
  client/src/presentation/components/snug/chat-container/index.tsx
  client/src/presentation/components/snug/chat-input-box/index.tsx
  client/src/presentation/components/snug/post-card/index.tsx
  client/src/presentation/components/snug/post-card/post-card-contents.tsx
  client/src/presentation/components/snug/thread-container/index.tsx
  client/src/presentation/components/snug/thread-input-box/index.tsx
  client/src/presentation/pages/snug/message-section/content.tsx
  client/src/presentation/pages/snug/thread/header/index.tsx
  client/src/presentation/pages/snug/thread/index.tsx
  server/.env.production
  server/ormconfig.js
  server/src/app.ts
  server/src/controller/api/common/messages.ts
  server/src/controller/api/post-controller.ts
  server/src/controller/api/profile-controller.ts
  server/src/domain/entity/Post.ts
  server/src/migration/1576297891945-CHANGE-POST-TO-MATERIALIZED-PATH.ts
  server/src/model/chat/chatter.ts
  server/src/model/chat/post-info.ts
  server/src/model/chat/reply-info.ts
  server/src/model/notifier/chat/chat-notifier.ts
  server/src/model/notifier/chat/post-notifier.ts
  server/src/model/notifier/chat/reply-notifier.ts
  server/src/routes/apiRouter.ts
  server/src/routes/channel/post/post-router.ts
  server/src/routes/post/post-router.ts
  server/src/routes/post/reply/reply-router.ts
  server/src/socket/common/events/publish-type.ts
Labels: devback, devfront, enhancement, feature

#192 패스파라미터 리랜더링 최적화 및 리팩토링
  client/src/core/service/auth-service.ts
  client/src/data/http/api/invite-api.ts
  client/src/data/repository/post-repository.ts
  client/src/data/repository/user-repository.ts
  client/src/presentation/components/snug/channel-list/channel-header.tsx
  client/src/presentation/components/snug/channel-list/channel-title.tsx
  client/src/presentation/components/snug/channel-plus-modal/channel-plus-modal-header.tsx
  client/src/presentation/components/snug/chat-container/index.tsx
  client/src/presentation/components/snug/chat-input-box/index.tsx
  client/src/presentation/pages/home/home-form.tsx
  client/src/presentation/pages/register-snug/modal.tsx
  client/src/presentation/pages/snug/index.tsx
  client/src/presentation/pages/snug/message-section/content.tsx
  client/src/presentation/pages/snug/message-section/header.tsx
  server/src/controller/api/post-controller.ts
  server/src/controller/api/snug-controller.ts
Labels: Refactor

#193 포스트카드 변경 및 메세지 생성시 프로필 매직 넘버 수정
  client/src/contexts/messages-context.tsx
  client/src/core/entity/post.tsx
  client/src/core/service/post-service.ts
  client/src/core/use-case/post-repository-type.ts
  client/src/data/http/api/post-api.ts
  client/src/data/repository/post-repository.ts
  client/src/presentation/components/snug/chat-input-box/index.tsx
  client/src/presentation/components/snug/post-card/file-contents.tsx
  client/src/presentation/components/snug/post-card/post-card-contents.tsx
  server/src/controller/api/post-controller.ts
  server/src/model/chat/chatter.ts
Labels: devback, devfront

#200 fix : 채팅 인풋을 텍스트 에어리어로 변경함
  client/src/App.tsx
  client/src/data/repository/post-repository.ts
  client/src/presentation/components/snug/chat-container/index.tsx
  client/src/presentation/components/snug/chat-input-box/index.tsx
  client/src/presentation/components/snug/post-card/post-card-contents.tsx
  client/src/presentation/pages/snug/message-section/content.tsx
Labels: Refactor, devfront

#203 프라이빗 채널 추가시, 사이드바에서 개인 채널로 분류되지 않는 이슈
  client/src/core/service/channel-service.ts
  client/src/core/use-case/channel-repository-type.ts
  client/src/data/http/api/channel-api.ts
  client/src/data/http/api/response/type/channel.ts
  client/src/data/repository/channel-repository.ts
  client/src/presentation/components/snug/channel-list/index.tsx
Labels: bug, devfront

#209 URL을 통해 스너그 페이지 입장 했을 때, 권한에 따라 입장
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/add-white.png
  client/src/assets/apple-touch-icon.png
  client/src/presentation/components/snug/channel-list/index.tsx
  client/src/presentation/components/snug/channel-list/side-button.tsx
  client/src/presentation/pages/error/index.tsx
  client/src/presentation/pages/home/home-detail-snug.tsx
  client/src/presentation/pages/invite-users/form/index.tsx
  client/src/presentation/pages/snug/auth.tsx
  client/src/presentation/pages/snug/index.tsx
  client/src/presentation/pages/snug/sidebar/index.tsx
Labels: bug, devfront

#210 Fix thread event
  client/src/presentation/components/snug/post-card/index.tsx
  client/src/presentation/components/snug/post-card/post-card-contents.tsx
Labels: bug, devfront

#212 fix : 로그아웃시 프로필 쿠키를 삭제하지 않는 버그를 고침
  client/src/core/service/auth-service.ts
  client/src/core/use-case/auth-repository-type.ts
  client/src/data/http/api/auth-api.ts
  client/src/data/repository/auth-repository.ts
  client/src/presentation/components/atomic-reusable/global-header.tsx
  server/src/controller/api/auth-controller.ts
  server/src/controller/api/common/messages.ts
  server/src/routes/auth/auth-router.ts
Labels: bug, devback, devfront

#214 HTTPS, 도메인 적용 및 배포 스크립트 추가
  client/.env
  client/src/contexts/socket-context.tsx
  client/src/data/http/api/axios-wrapper.ts
  deploy/deploy.sh
  deploy/teardown.sh
  server/.env.production
  server/.key/.gitkeep
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controller/index-controller.ts
  server/src/routes/index.ts
  server/src/server.ts
  server/src/socket/socket-manager.ts
  server/src/utils/http-helper.ts
  server/src/utils/url-info.ts
Labels: devback, devfront, feature

#219 Fix snug list & 페이지 네이션
  client/src/App.tsx
  client/src/contexts/messages-context.tsx
  client/src/core/service/post-service.ts
  client/src/core/use-case/post-repository-type.ts
  client/src/data/http/api/post-api.ts
  client/src/data/repository/post-repository.ts
  client/src/presentation/components/atomic-reusable/global-header.tsx
  client/src/presentation/components/snug/channel-list/channel-title.tsx
  client/src/presentation/components/snug/channel-list/side-button.tsx
  client/src/presentation/components/snug/chat-container/index.tsx
  client/src/presentation/components/snug/chat-input-box/index.tsx
  client/src/presentation/pages/home/home-detail-snug.tsx
  client/src/presentation/theme/color-theme.ts
Labels: bug, devfront

#218 fix : 디자인을 수정함 black=> white
  client/src/App.tsx
  client/src/assets/arrow-down-sign-white.png
  client/src/assets/arrow-down-sign.png
  client/src/assets/at-white.png
  client/src/assets/clip-white.png
  client/src/assets/clip.png
  client/src/assets/dubu.png
  client/src/assets/face-white.png
  client/src/assets/letter-x-white.png
  client/src/assets/letter-x.png
  client/src/assets/more.png
  client/src/contexts/messages-context.tsx
  client/src/core/service/post-service.ts
  client/src/core/use-case/post-repository-type.ts
  client/src/data/http/api/post-api.ts
  client/src/data/repository/post-repository.ts
  client/src/presentation/components/atomic-reusable/custom-drop-down.tsx
  client/src/presentation/components/atomic-reusable/custom-input.tsx
  client/src/presentation/components/atomic-reusable/custom-modal.tsx
  client/src/presentation/components/atomic-reusable/global-header.tsx
  client/src/presentation/components/atomic-reusable/icon-box.tsx
  client/src/presentation/components/atomic-reusable/page-layout.tsx
  client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-information.tsx
  client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-item.tsx
  client/src/presentation/components/snug/channel-browse-modal/index.tsx
  client/src/presentation/components/snug/channel-list/channel-title.tsx
  client/src/presentation/components/snug/channel-list/index.tsx
  client/src/presentation/components/snug/channel-list/side-button.tsx
  client/src/presentation/components/snug/channel-plus-modal/channel-plus-modal-header.tsx
  client/src/presentation/components/snug/channel-plus-modal/index.tsx
  client/src/presentation/components/snug/chat-container/index.tsx
  client/src/presentation/components/snug/chat-input-box/index.tsx
  client/src/presentation/components/snug/file-upload-modal/index.tsx
  client/src/presentation/components/snug/post-card/file-contents.tsx
  client/src/presentation/components/snug/post-card/post-card-contents.tsx
  client/src/presentation/components/snug/thread-input-box/index.tsx
  client/src/presentation/pages/home/home-detail-snug.tsx
  client/src/presentation/pages/home/home-form.tsx
  client/src/presentation/pages/snug/auth.tsx
  client/src/presentation/pages/snug/header/index.tsx
  client/src/presentation/pages/snug/index.tsx
  client/src/presentation/pages/snug/message-section/content.tsx
  client/src/presentation/pages/snug/message-section/header.tsx
  client/src/presentation/pages/snug/message-section/index.tsx
  client/src/presentation/pages/snug/profile/index.tsx
  client/src/presentation/pages/snug/profile/modal/index.tsx
  client/src/presentation/pages/snug/profile/modal/modal-header.tsx
  client/src/presentation/pages/snug/sidebar/index.tsx
  client/src/presentation/pages/snug/thread/header/index.tsx
  client/src/presentation/pages/snug/thread/index.tsx
  client/src/presentation/theme/color-theme.ts
  server/src/server.ts
Labels: bug, devfront

#217 첫 번째 댓글의 카운트가 노출되지 않는 이슈
  client/src/presentation/components/snug/post-card/post-card-contents.tsx
  client/src/presentation/components/snug/thread-input-box/index.tsx
  server/src/controller/api/common/request/identifier/snug-identifier.ts
  server/src/controller/api/invite-controller.ts
Labels: bug, devfront

#216 TypeORM 커넥션에서 Time Zone, Charset 설정하도록 변경
  server/.env.production
  server/ormconfig.js
Labels: bug, devback

#215 다중 프로세스 지원하는 pm2 인하여 Socket Room 의 정합성이 맞지 않아 메시지가 오지 않는 이슈
  server/.env.production
  server/package.json
  server/src/server.ts
  server/src/utils/http-helper.ts
Labels: bug

#221 채널 목록 조회 모달에서 Title, Sort 기준이 적용되지 않는 이슈
  client/src/core/service/channel-service.ts
  client/src/core/use-case/channel-repository-type.ts
  client/src/data/http/api/channel-api.ts
  client/src/data/repository/channel-repository.ts
  client/src/presentation/components/atomic-reusable/custom-drop-down.tsx
  client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-dropdown.tsx
  client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-sort-list.tsx
  client/src/presentation/components/snug/channel-browse-modal/index.tsx
  client/src/presentation/components/snug/channel-list/index.tsx
  server/src/controller/api/channel-controller.ts
  server/src/domain/entity/Room.ts
  server/src/model/participant/participant.ts
  server/src/server.ts
Labels: bug, devback, devfront

#220 스너그 입장시 profile ID를 기준으로 room에 join 및 leave 기능 수정
  client/src/contexts/socket-context.tsx
  client/src/presentation/components/snug/channel-list/channel-title.tsx
  client/src/presentation/components/snug/channel-plus-modal/channel-plus-modal-contents.tsx
  client/src/presentation/pages/snug/auth.tsx
  client/src/presentation/pages/snug/index.tsx
  server/src/server.ts
  server/src/socket/action/snug.ts
  server/src/socket/common/events/consume-type.ts
  server/src/socket/listener/connection.ts
  server/src/socket/socket-manager.ts
Labels: bug

#222 Message Input Box 중앙 정렬되도록 CSS 변경
  client/src/presentation/components/atomic-reusable/custom-drop-down.tsx
  client/src/presentation/components/snug/chat-input-box/index.tsx
Labels: bug, devfront

#223 Posts Default Reverse 수정
  client/src/contexts/messages-context.tsx
  client/src/presentation/components/snug/chat-container/index.tsx
  server/src/model/chat/chatter.ts
Labels: bug, devback, devfront

#225 현재 Thread 와 상관없는 reply 와 로그인 화면에 알림 컴포넌트 노출되는 이슈
  client/src/core/service/auth-service.ts
  client/src/core/use-case/auth-repository-type.ts
  client/src/data/http/api/auth-api.ts
  client/src/data/repository/auth-repository.ts
  client/src/presentation/components/atomic-reusable/global-header.tsx
  client/src/presentation/components/snug/chat-container/index.tsx
  client/src/presentation/components/snug/thread-input-box/index.tsx
  client/src/presentation/pages/home/home-form.tsx
  server/src/controller/api/auth-controller.ts
  server/src/routes/auth/auth-router.ts
  server/src/validator/identifier-validator.ts
Labels: bug, devfront

#226 Hotfix/1.0.1
  client/src/presentation/components/invitation-alarm/index.tsx
  client/src/presentation/components/snug/post-card/post-card-contents.tsx
  client/src/presentation/components/snug/thread-input-box/index.tsx
  client/src/presentation/pages/invite-users/form/invite-users.tsx
Labels: bug, devfront

#228 채널 목록 조회시 중복된 퍼블릭 채널을 조회하는 이슈
  client/src/presentation/components/atomic-reusable/global-header.tsx
  client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-item.tsx
  client/src/presentation/components/snug/channel-list/channel-header.tsx
  client/src/presentation/components/snug/channel-plus-modal/channel-plus-modal-contents.tsx
  client/src/presentation/pages/snug/message-section/content.tsx
  server/src/controller/api/channel-controller.ts
  server/src/model/participant/participant.ts
  server/src/routes/snug/channel/channel-router.ts
Labels: bug, devback, devfront
