Repository connect-foundation/2019-08, pull requests merged in 2019-11, with the labels that each got.

#17 Merged By @GiPyoo Reviewd By @GiPyoo @raccoonback
  client/src/assets/hash-white.png
  client/src/assets/letter-x-white.png
  client/src/assets/plus-white.png
  client/src/presentation/components/channel-header.tsx
  client/src/presentation/components/channel-list.tsx
  client/src/presentation/components/channel-plus-modal-contents.tsx
  client/src/presentation/components/channel-plus-modal-header.tsx
  client/src/presentation/components/channel-plus-modal.tsx
  client/src/presentation/components/channel-title.tsx
  client/src/presentation/components/custom-button.tsx
  client/src/presentation/components/custom-input.tsx
  client/src/presentation/components/custom-on-off-button.tsx
  client/src/presentation/components/sidebar.tsx
Labels: devfront, feature

#27 [WIP] 채널 생성 기능 구현 (#27) Merged By @GiPyoo Reviewed By @GiPyoo
  client/.env
  client/jest.config.js
  client/package-lock.json
  client/package.json
  client/src/@context/http-providers/http-providers.tsx
  client/src/@context/repositories/chat-room.ts
  client/src/@context/repositories/index.tsx
  client/src/@context/services/index.tsx
  client/src/context.instance.tsx
  client/src/core/common/string-helper.ts
  client/src/core/entity/channel.ts
  client/src/core/entity/doc.md
  client/src/core/model/channel-model.ts
  client/src/core/service/channel-service.ts
  client/src/core/service/doc.md
  client/src/core/use-case/channel-repository-type.ts
  client/src/data/http/api/axios-wrapper.ts
  client/src/data/http/api/channel-api.ts
  client/src/data/http/api/response/ResponseEntity.ts
  client/src/data/http/api/status-codes.ts
  client/src/data/http/doc.md
  client/src/data/repository/channel-repository.ts
  client/src/data/repository/doc.md
  client/test/core/common/string-helper.test.ts
  client/test/core/service/channel-service.test.ts
  client/test/data/http/api/channel-api.test.ts
  client/tsconfig.json
Labels: devfront, feature

#28 모달창 연결
  client/src/assets/arrow-down-sign-white.png
  client/src/contexts/channel-context.tsx
  client/src/contexts/modal-context.tsx
  client/src/presentation/components/atomic-reusable/custom-button.tsx
  client/src/presentation/components/atomic-reusable/custom-input.tsx
  client/src/presentation/components/atomic-reusable/custom-on-off-button.tsx
  client/src/presentation/components/atomic-reusable/icon-box.tsx
  client/src/presentation/components/snug/channel-list/channel-header.tsx
  client/src/presentation/components/snug/channel-list/channel-title.tsx
  client/src/presentation/components/snug/channel-list/index.tsx
  client/src/presentation/components/snug/channel-plus-modal/channel-plus-modal-contents.tsx
  client/src/presentation/components/snug/channel-plus-modal/channel-plus-modal-header.tsx
  client/src/presentation/components/snug/channel-plus-modal/index.tsx
  client/src/presentation/components/snug/chat-container/index.tsx
  client/src/presentation/components/snug/chat-input-box/index.tsx
  client/src/presentation/components/snug/message-card/index.tsx
  client/src/presentation/components/snug/message-card/message-card-contents.tsx
  client/src/presentation/pages/snug/index.tsx
  client/src/presentation/pages/snug/message-section/content.tsx
  client/src/presentation/pages/snug/sidebar/index.tsx
Labels: devfront, feature

#26 pull request format 지정 (#26) Merged By @Gipyoo
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#34 @context/services/index.tsx 에서 ChannelService 를 임포트하지 못하는 이슈 해결
  client/src/@context/services/index.tsx
Labels: bug, devfront

#38 TypeORM 설정
  server/.env.template
  server/jest.config.js
  server/ormconfig.js
  server/ormconfig.json
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/entity/Channel.ts
  server/src/entity/User.ts
  server/src/migration/1574194015940-ADD-CHANNEL.ts
  server/src/migration/test.txt
  server/src/routes/index.ts
  server/test/app.test.ts
  server/test/index.test.ts
  server/test/ormconfig.test.ts
  server/tsconfig.json
Labels: devback

#43 서버 구조 설계
  server/.env.template
  server/.gitignore
  server/jest.config.js
  server/ormconfig.js
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/entity/Channel.ts
  server/src/index/controller.ts
  server/src/index/index.controller.ts
  server/src/migration/1574194015940-ADD-CHANNEL.ts
  server/src/routes/index.ts
  server/src/server.ts
  server/test/app.test.ts
  server/test/index.test.ts
  server/test/ormconfig.test.ts
  server/tsconfig.json
Labels: devback

#39 채널에 들어갔을 때 메세지를 가져오고 메세지를 생성하는 페치 구현
  client/src/@context/http-providers/http-providers.tsx
  client/src/@context/repositories/chat-room.ts
  client/src/@context/repositories/index.tsx
  client/src/@context/repositories/posting.ts
  client/src/@context/services/index.tsx
  client/src/contexts/messages-context.tsx
  client/src/core/entity/channel.ts
  client/src/core/entity/message.tsx
  client/src/core/entity/post.tsx
  client/src/core/model/channel-model.ts
  client/src/core/service/post-service.ts
  client/src/core/use-case/channel-repository-type.ts
  client/src/core/use-case/post-repository-type.ts
  client/src/data/http/api/axiosErrorHandler.ts
  client/src/data/http/api/channel-api.ts
  client/src/data/http/api/post-api.ts
  client/src/data/repository/post-repository.ts
  client/src/presentation/components/atomic-reusable/profile-thumnail.tsx
  client/src/presentation/components/snug/chat-container/index.tsx
  client/src/presentation/components/snug/chat-input-box/index.tsx
  client/src/presentation/components/snug/message-card/index.tsx
  client/src/presentation/components/snug/post-card/index.tsx
  client/src/presentation/components/snug/post-card/post-card-contents.tsx
Labels: devfront, feature

#55 fix : 동작오류로인한 핫픽스
  client/src/presentation/components/snug/chat-container/index.tsx
  client/src/presentation/components/snug/chat-input-box/index.tsx
  client/src/presentation/components/snug/message-card/message-card.tsx
  client/src/presentation/components/snug/post-card/index.tsx
Labels: bug

#59 이름 기준으로 채널 조회하는 기능 추가
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controllers/apis/channel-api-controller.ts
  server/src/entity/Channel.ts
  server/src/routes/chnnel-router.ts
  server/src/server.ts
  server/test/integrate/apis/channel-api-controller.test.ts
  server/test/ormconfig.test.ts
Labels: devback, feature

#58 스타일 컴포넌트 테마를 활용한 전역적 스타일 관리
  client/src/App.tsx
  client/src/presentation/components/atomic-reusable/custom-button.tsx
  client/src/presentation/components/atomic-reusable/custom-drop-down.tsx
  client/src/presentation/components/atomic-reusable/custom-modal.tsx
  client/src/presentation/components/atomic-reusable/icon-box.tsx
  client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-dropdown.tsx
  client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-header.tsx
  client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-information.tsx
  client/src/presentation/components/snug/channel-browse-modal/index.tsx
  client/src/presentation/components/snug/channel-list/channel-header.tsx
  client/src/presentation/components/snug/channel-list/channel-title.tsx
  client/src/presentation/components/snug/channel-list/index.tsx
  client/src/presentation/components/snug/channel-plus-modal/channel-plus-modal-contents.tsx
  client/src/presentation/components/snug/channel-plus-modal/index.tsx
  client/src/presentation/components/snug/chat-input-box/index.tsx
  client/src/presentation/components/snug/post-card/index.tsx
  client/src/presentation/pages/snug/index.tsx
  client/src/presentation/pages/snug/message-section/content.tsx
  client/src/presentation/pages/snug/message-section/header.tsx
  client/src/presentation/pages/snug/message-section/index.tsx
  client/src/presentation/pages/snug/sidebar/index.tsx
  client/src/presentation/theme/color-theme.ts
Labels: devfront

#71 StringHelper 객체를 Utility 로 변경(#71) Merged By @GiPyoo Reviewed By @GiPyoo
  client/src/core/common/string-helper.ts
  client/src/core/entity/channel.ts
  client/src/core/model/channel-model.ts
  client/src/core/service/channel-service.ts
  client/src/core/utility/string-helper.ts
  client/src/data/http/api/channel-api.ts
  client/test/core/common/string-helper.test.ts
  client/test/core/service/channel-service.test.ts
  client/test/data/http/api/channel-api.test.ts
Labels: bug, devfront

#70 포스트 생성 api
  server/package.json
  server/src/app.ts
  server/src/controllers/apis/post-api-controller.ts
  server/src/entity/Channel.ts
  server/src/entity/ParticipateIn.ts
  server/src/entity/Post.ts
  server/src/entity/Profile.ts
  server/src/entity/Room.ts
  server/src/entity/Snug.ts
  server/src/entity/User.ts
  server/src/migration/1574194015940-ADD-CHANNEL.ts
  server/src/migration/1574745011724-ADD-PROFILE.ts
  server/src/migration/1574745035521-ADD-ROOM.ts
  server/src/migration/1574745189357-ADD-POST.ts
  server/src/migration/1574746206264-ADD-SNUG.ts
  server/src/migration/1574746492050-ADD-USER.ts
  server/src/migration/1574748267870-ADD-PARTICIPATEIN.ts
  server/src/migration/1574749093761-CHANGE-NAME.ts
  server/src/routes/post-router.ts
Labels: API, devback

#57 로그인 UI 작성
  client/src/App.tsx
  client/src/assets/notification.png
  client/src/presentation/components/atomic-reusable/custom-button.tsx
  client/src/presentation/components/atomic-reusable/custom-input.tsx
  client/src/presentation/components/atomic-reusable/custom-login-input.tsx
  client/src/presentation/components/atomic-reusable/global-header.tsx
  client/src/presentation/components/atomic-reusable/page-layout.tsx
  client/src/presentation/pages/home/home-detail-snug.tsx
  client/src/presentation/pages/home/home-form.tsx
  client/src/presentation/pages/home/home-snug.tsx
  client/src/presentation/pages/home/index.tsx
  client/src/presentation/pages/register-snug/index.tsx
  client/src/presentation/pages/register-snug/register-snug-form.tsx
  client/src/presentation/pages/register-user/index.tsx
  client/src/presentation/pages/register-user/register-user-form.tsx
Labels: devfront

#67 [Refactor] 포스트카드 리팩토링
  client/src/presentation/components/atomic-reusable/profile-thumnail.tsx
  client/src/presentation/components/snug/chat-container/index.tsx
  client/src/presentation/components/snug/post-card/index.tsx
  client/src/presentation/components/snug/post-card/post-card-contents.tsx
Labels: devfront

#61 Feature create channel
  client/src/presentation/components/snug/channel-plus-modal/channel-plus-modal-contents.tsx
  client/src/presentation/components/snug/channel-plus-modal/index.tsx
  client/src/presentation/components/snug/modals/index.tsx
  client/src/presentation/pages/snug/index.tsx
  client/src/prop-types/application-type.ts
Labels: devfront, feature

#63 채널 생성 API
  server/src/app.ts
  server/src/controllers/apis/channel-api-controller.ts
  server/src/routes/chnnel-router.ts
  server/test/integrate/apis/channel-api-controller.test.ts
Labels: devfront

#65 Feature channel list
  1
  client/.env
  client/package.json
  client/src/App.tsx
  client/src/contexts/channel-context.tsx
  client/src/core/common/string-helper.ts
  client/src/core/entity/channel.ts
  client/src/core/model/channel-model.ts
  client/src/core/service/channel-service.ts
  client/src/core/use-case/channel-repository-type.ts
  client/src/core/utility/string-helper.ts
  client/src/data/http/api/axios-wrapper.ts
  client/src/data/http/api/channel-api.ts
  client/src/data/repository/channel-repository.ts
  client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-sort-list.tsx
  client/src/presentation/components/snug/channel-list/index.tsx
  client/src/presentation/components/snug/channel-plus-modal/channel-plus-modal-contents.tsx
  client/src/presentation/pages/snug/sidebar/index.tsx
  client/test/core/common/string-helper.test.ts
  client/test/core/service/channel-service.test.ts
  client/test/data/http/api/channel-api.test.ts
Labels: devfront, feature

#69 채널 메시지 목록 조회 기능 추가
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controller/api/channel-controller.ts
  server/src/controller/api/common/order.ts
  server/src/controller/api/common/paginator.ts
  server/src/controller/api/post-controller.ts
  server/src/entity/Base.ts
  server/src/entity/Post.ts
  server/src/entity/Profile.ts
  server/src/entity/Room.ts
  server/src/entity/Snug.ts
  server/src/entity/User.ts
  server/src/routes/channel/chnnel-router.ts
  server/src/routes/channel/post/post-router.ts
  server/src/routes/chnnel-router.ts
  server/src/routes/index.ts
  server/src/routes/post/post-router.ts
  server/src/validator/identifier-validator.ts
  server/test/integrate/api/channel-controller.test.ts
  server/test/integrate/api/post-controller.test.ts
  server/test/unit/controller/api/common/order.test.ts
  server/test/unit/controller/api/common/paginator.test.ts
  server/test/unit/controller/channel-controller.test.ts
  server/test/unit/controller/post-controller.test.ts
  server/test/unit/validator/identifier-validator.test.ts
Labels: devback, feature

#74 fix : 잘못되어있는 환경변수 설정을 수정함
  client/.env.development
  client/src/App.tsx
Labels: bug, devfront

#82 유지 보수를 고려하여 socket 모듈 구조 변경
  server/src/controller/api/channel-controller.ts
  server/src/controller/api/common/error-message.ts
  server/src/controller/api/common/status-code.ts
  server/src/controller/api/post-controller.ts
  server/src/server.ts
  server/src/socket/action/room.ts
  server/src/socket/common/events/consume-type.ts
  server/src/socket/common/events/publish-type.ts
  server/src/socket/listener/connection.ts
  server/src/socket/socket-manager.ts
  server/src/socketConfig.ts
  server/src/utils/response-form.ts
  server/src/utils/responseForm.ts
  server/test/integrate/channel/channel-controller.test.ts
  server/test/integrate/channel/post/post-controller.test.ts
  server/test/unit/controller/channel-controller.test.ts
  server/test/unit/controller/post-controller.test.ts
Labels: devback, enhancement

#81 클라이언트 소켓 및 페치 기능을 ui에 연결 및 구현
  client/.env.development
  client/src/contexts/channel-context.tsx
  client/src/contexts/messages-context.tsx
  client/src/contexts/path-parameter-context.tsx
  client/src/core/entity/path-parameter.ts
  client/src/core/service/channel-service.ts
  client/src/core/use-case/channel-repository-type.ts
  client/src/data/repository/channel-repository.ts
  client/src/presentation/components/snug/channel-list/channel-title.tsx
  client/src/presentation/components/snug/channel-list/index.tsx
  client/src/presentation/components/snug/channel-plus-modal/channel-plus-modal-contents.tsx
  client/src/presentation/components/snug/chat-container/index.tsx
  client/src/presentation/components/snug/chat-input-box/index.tsx
  client/src/presentation/pages/snug/index.tsx
  client/src/presentation/pages/snug/message-section/content.tsx
Labels: devfront, feature

#77 Post 생성 API 요청 후 SocketIO을 이용한 event 생성
  server/package-lock.json
  server/package.json
  server/src/controller/api/channel-controller.ts
  server/src/controller/api/common/error-message.ts
  server/src/controller/api/common/status-code.ts
  server/src/controller/api/post-controller.ts
  server/src/controllers/apis/post-api-controller.ts
  server/src/server.ts
  server/src/socket/action/room.ts
  server/src/socket/common/events/consume-type.ts
  server/src/socket/common/events/publish-type.ts
  server/src/socket/listener/connection.ts
  server/src/socket/socket-manager.ts
  server/src/utils/response-form.ts
  server/test/integrate/channel/channel-controller.test.ts
  server/test/integrate/channel/post/post-controller.test.ts
  server/test/unit/controller/channel-controller.test.ts
  server/test/unit/controller/post-controller.test.ts
Labels: devback, feature

#73 채널 목록을 조회하는 api 구현
  1
  server/src/app.ts
  server/src/controller/api/channel-controller.ts
  server/src/controller/api/common/error-message.ts
  server/src/controller/api/common/status-code.ts
  server/src/middleware/errorHandler.ts
  server/src/routes/channel/channel-router.ts
  server/src/util/HttpException.ts
  server/tsconfig.json
Labels: devback

#83 fix : 채팅 렌더링이 중복되는 이슈를 해결함
  .vscode/launch.json
  client/.env.development
  client/src/App.tsx
  client/src/data/http/api/post-api.ts
  client/src/data/repository/post-repository.ts
  client/src/presentation/components/snug/chat-container/index.tsx
  client/src/presentation/components/snug/chat-input-box/index.tsx
  server/src/controller/api/post-controller.ts
Labels: bug

#84 Channel 대한 메시지 목록에 프로필 정보가 포함되지 않는 이슈
  server/src/controller/api/common/paginator.ts
  server/src/entity/Post.ts
  server/test/integrate/channel/post/post-controller.test.ts
Labels: bug, devback

#86 Refactor design
  client/src/App.tsx
  client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-item.tsx
  client/src/presentation/components/snug/channel-browse-modal/channel-browse-modal-sort-list.tsx
  client/src/presentation/components/snug/channel-browse-modal/index.tsx
  client/src/presentation/components/snug/chat-container/index.tsx
  client/src/presentation/pages/home/home-detail-snug.tsx
  client/src/presentation/pages/snug/header/index.tsx
  client/src/presentation/pages/snug/message-section/content.tsx
Labels: devfront
